server:
  address: 0.0.0.0
  port: 8808

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yunqi_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    property-naming-strategy: LOWER_CASE

#JWT
jwt:
  header: Authorization
  secret: Jesse777Xue
  expiration: 604800
  #以此字段作为Authorization值的开头，后面要有空格隔开
  tokenHead: "Rabbit "
  route:
    authentication:
    path: auth
    refresh: refresh
    register: "auth/register"
logging:
  level:
    com.yunqi.cloudenglish: debug
  file: log/cloudenglish.log
  path: log/

#log

